name: Source Code License Audit Example
on:
  workflow_dispatch:

permissions:
  id-token: write

env:
  JF_URL: ${{ vars.JF_URL }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          oidc-provider-name: 'github-oidc-integration'
          oidc-audience: 'jfrog-github'

      - name: JF Maven Configure
        run: |
          jf mvn-config \
          --server-id-resolve=setup-jfrog-cli-server \
          --server-id-deploy=setup-jfrog-cli-server \
          --repo-resolve-releases=mavencentral-remote \
          --repo-resolve-snapshots=mavencentral-remote \
          --repo-deploy-releases=mavencentral-remote \
          --repo-deploy-snapshots=mavencentral-remote \
          --use-wrapper=true

      - name: Source Code Audit
        run: |
          jf audit --mvn --licenses

      - name: Source Code Audit With Scoped Watch
        run: |
          jf audit --mvn --licenses --watches=license-demo-watch --fail=false

      - name: Source Code Audit in JSON Format & Scoped to Project Watches
        run: |
          jf audit --mvn --licenses --format=json --fail=false --project=licensedemo
